version: '3.8'
services:
  api:
    build: .
    container_name: go-rest-example-api
    ports:
      - "8080:8080"
    environment:
      MONGODB_URI: mongodb://admin:pass@mongodb:27017/
      PORT: 8080
      JWT_TOKEN: supersecrettesttoken
    networks:
      - go-rest-api-example
    depends_on:
      - mongodb
  mongodb:
    image: mongo
    container_name: mongo-local
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    networks:
      - go-rest-api-example
  db-client:
    container_name: mongo-express
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_MONGODB_URL=mongodb://admin:pass@mongodb:27017/
    depends_on:
      - mongodb
    networks:
      - go-rest-api-example
volumes:
  mongodata:

networks:
  go-rest-api-example: {}